#!/usr/bin/python
#########################################################################################
# Copyright 2020 by Heqing Huang (heqinghuangusc@gmail.com)
#
# Project: Simple CSR Generator
# Author: Heqing Huang
# Created: 11/01/2020
#
# Description:
#   The main executable
#
#########################################################################################

import sys
import os
sys.dont_write_bytecode = True

my_path = os.path.dirname(os.path.realpath(__file__))
sys.path.append(my_path + '/src')

from main import *

main()